// Generated by https://quicktype.io

export interface Customer {
  id: number;
  name: string;
  phone: string;
  email: string;
  birthday: string;
  address: string;
  notes: string;
  picture: string;
  gender: string;
}
