// Generated by https://quicktype.io

export interface Menu {
  id: number;
  nombre_plato: string;
  descripcion_plato: string;
  id_categoria: number;
  precio_venta: number;
  costo_produccion: number;
  ingredientes: Ingrediente[];
  alergenos: string[];
  imagen_plato: string;
}

export interface Ingrediente {
  nombre_ingrediente: string;
  cantidad: number;
}
